### ISSUE TITLE
Improve docs for image proxy cache

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#522]
Relates to: https://github.com/torrust/torrust-index-gui/discussions/519

Images in the torrent description only show if the user is logged in. If the user is not logged in, you see something like:

![image](https://github.com/torrust/torrust-index-gui/assets/58816/c3578d24-961f-4e31-a546-da0e1383c80d)

Images are served using a proxy cache to preserve the user's privacy. If we served images directly from the original URL, a malicious user could track other users' activity by tracking served images.

Since the proxy takes a lot of resources from the server, we decided to assign a quota per user that you can config in the config file:

```toml
[image_cache]
max_request_timeout_ms = 1000
capacity = 128000000
entry_size_limit = 4000000
user_quota_period_seconds = 3600
user_quota_bytes = 64000000
```

We also need to identify the user to update the quota.

Docs for image configuration: https://docs.rs/torrust-index/3.0.0-alpha.2/torrust_index/config/struct.ImageCache.html

We should add this explanation to the [User Guide](https://github.com/torrust/torrust-index-gui/blob/develop/docs/user_guide.md) and also to the crates docs.

Maybe we should also add a link to the [User Guide](https://github.com/torrust/torrust-index-gui/blob/develop/docs/user_guide.md) in the application.
