### ISSUE TITLE
Update Index configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#581]
Relates to: https://github.com/torrust/torrust-index/issues/591

New changes have been made to the Torrust Index config file. Some API endpoints exposing the configuration have also changed. We have to apply those changes here.

- Update config files
- Update Typescript libs:
  - https://github.com/torrust/torrust-index-api-lib
  - https://github.com/torrust/torrust-index-types-lib
- Update code referencing changes in the API response

### Old version

```toml
[logging]
log_level = "info"

[tracker]
mode = "public"
```

### New version

```toml
version = "2"

[logging]
threshold = "info"

[tracker]
private = false
listed = false
```
