### ISSUE TITLE
Update Iindex TOML config file

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#587]
Relates to: https://github.com/torrust/torrust-index/pull/670

These two config option in the Index TOML config file have been removed:

```toml
[auth]
email_on_signup = "optional"

[mail]
email_verification_enabled = false
```

We need to replace them with:

```toml
[registration]
[registration.email]
#required = false
#verified = false
```
