### ISSUE TITLE
Update Index configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#591]
Depends on: 
 - https://github.com/torrust/torrust-index/issues/653
 - https://github.com/torrust/torrust-index/issues/673
 - https://github.com/torrust/torrust-index/issues/672

After finishing the [last configuration changes in the Index](https://github.com/torrust/torrust-index/issues/591), those last changes must be applied here.

1. The `metadata` section was changed:

```toml
[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"
```

2. `secret_key` option was renamed to  `user_claim_token_pepper`.

3. And some options were made mandatory:

```toml
[metadata]
schema_version = "2.0.0"

[logging]
threshold = "info"
```

4. Env var changed

From `TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__SECRET_KEY` to  `TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__USER_CLAIM_TOKEN_PEPPER`
