### ISSUE TITLE
Settings are not loaded correctly

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-index-gui#98]
There have been some changes in the Index Backend configuration file that have not been applied here in the frontend.

- There are new options in `auth` section: `min_password_length`, `max_password_length`, `secret_key`.
- The option `Torrent Status Update Interval (seconds)` in the backend config.toml file was moved from section `database` to a new section `tracker_statistics_importer`.
- Emaikl tab show the `Torrent Status Update Interval (seconds)` option, which belongs to the new section `tracker_statistics_importer`.

The current config file for the backend:

```toml
log_level = "info"

[website]
name = "Torrust2"

[tracker]
url = "udp://tracker:6969"
mode = "Public"
api_url = "http://localhost:1212"
token = "MyAccessToken"
token_valid_seconds = 7257600

[net]
port = 3000

[auth]
email_on_signup = "Optional"
min_password_length = 6
max_password_length = 64
secret_key = "MaxVerstappenWC2021"

[database]
connect_url = "sqlite://data.db?mode=rwc"

[mail]
email_verification_enabled = false
from = "example@email.com"
reply_to = "noreply@email.com"
username = ""
password = ""
server = "0.0.0.0"
port = 1025

[image_cache]
max_request_timeout_ms = 1000
capacity = 128000000
entry_size_limit = 4000000
user_quota_period_seconds = 3600
user_quota_bytes = 64000000

[api]
default_torrent_page_size = 10
max_torrent_page_size = 30

[tracker_statistics_importer]
torrent_info_update_interval = 3600
```

Before fixing this issue, please read this discussion: https://github.com/torrust/torrust-index-frontend/discussions/94. It might not make sense to fix it if we remove it totally.
